author: Supermaxman
main: me.supermaxman.xechat.XeChat
name: XeChat
version: '1.0.1'
commands:
    local:
        description: Switch to local chat.
        usage: /<command>
    chreload:
        description: Reloads XeChat Config.
        usage: /<command>
    global:
        description: Switch to global chat.
        usage: /<command>
    trade:
        description: Switch to trade chat.
        usage: /<command>
    z:
        description: Switch to staff chat.
        usage: /<command>
    create:
        description: Create channels
        usage: /<command>
    join:
        description: Join channels
        usage: /<command>
    delete:
        description: Deletes channels
        usage: /<command>
    leave:
        description: Leaves channels
        usage: /<command>
    chlist:
        description: Lists channels
        usage: /<command>
    channellist:
        description: Lists channels
        usage: /<command>
    tell:
        description: Private whisper
        usage: /<command>
    msg:
        description: Private whisper
        usage: /<command>
    whisper:
        description: Private whisper
        usage: /<command>
    r:
        description: Private reply
        usage: /<command>
    reply:
        description: Private reply
        usage: /<command>
    where:
        description: Where you are
        usage: /<command>
    rank:
        description: What rank a player is
        usage: /<command>
    ch:
        description: For the noobs
        usage: /<command>
        