author: Supermaxman
main: me.supermaxman.xechat.XeChat
name: XeChat
version: '1.0.1'
commands:
    l:
        description: Switch to local chat.
        usage: /<command>
    g:
        description: Switch to global chat.
        usage: /<command>
    t:
        description: Switch to trade chat.
        usage: /<command>