author: Supermaxman
main: me.supermaxman.xechat.XeChat
name: XeChat
version: '1.0.1'
commands:
    l:
        description: Switch to local chat.
        usage: /<command>
    g:
        description: Switch to global chat.
        usage: /<command>
    trade:
        description: Switch to trade chat.
        usage: /<command>
    z:
        description: Switch to staff chat.
        usage: /<command>
    create:
        description: Create channels
        usage: /<command>
    join:
        description: Join channels
        usage: /<command>
    delete:
        description: Deletes channels
        usage: /<command>
    leave:
        description: Leaves channels
        usage: /<command>
     clist:
        description: Leaves channels
        usage: /<command>
      channellist:
        description: Leaves channels
        usage: /<command>